name: seefood
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - asn1crypto=1.2.0
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - automat=0.7.0
  - backcall=0.1.0
  - bcrypt=3.1.7
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.13.0
  - cloudpickle=1.2.2
  - constantly=15.1.0
  - cryptography=2.7
  - cssselect=1.1.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.8.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.0
  - hyperlink=17.3.1
  - icu=64.2
  - idna=2.8
  - imageio=2.6.1
  - importlib_metadata=0.23
  - incremental=17.5.0
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.14.0
  - jpeg=9c
  - json5=0.8.5
  - jsonschema=3.1.1
  - jupyter_client=5.3.3
  - jupyter_core=4.5.0
  - jupyterlab=1.1.4
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - libtiff=4.0.10
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvm-openmp=8.0.1
  - lxml=4.4.1
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - more-itertools=7.2.0
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.4
  - ninja=1.9.0
  - notebook=6.0.1
  - numpy=1.17.2
  - olefile=0.46
  - openssl=1.1.1d
  - packaging=19.2
  - pandas=0.25.2
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parsel=1.5.2
  - parso=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=19.3.1
  - pluggy=0.13.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - ptyprocess=0.6.0
  - py=1.8.0
  - pyasn1=0.4.6
  - pyasn1-modules=0.2.7
  - pycparser=2.19
  - pydispatcher=2.0.5
  - pygments=2.4.2
  - pyhamcrest=1.9.0
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - pytest=5.0.1
  - pytest-runner=5.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytorch=1.3.0
  - pytz=2019.3
  - pywavelets=1.1.1
  - pyzmq=18.1.0
  - queuelib=1.5.0
  - readline=8.0
  - scikit-image=0.16.2
  - scikit-learn=0.21.3
  - scipy=1.3.2
  - scrapy=1.7.3
  - send2trash=1.5.0
  - service_identity=18.1.0
  - setuptools=41.4.0
  - six=1.12.0
  - sqlite=3.30.1
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.10.0
  - torchvision=0.4.1
  - tornado=6.0.3
  - tqdm=4.36.1
  - traitlets=4.3.3
  - twisted=19.7.0
  - urllib3=1.25.7
  - w3lib=1.21.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wordcloud=1.6.0
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - zope.interface=4.6.0
  - zstd=1.4.3
  - pip:
    - beautifulsoup4==4.8.1
    - icrawler==0.6.2
    - soupsieve==1.9.4

